dasboard_user:
    path: /
    controller: App\Controller\ComunUserController::index

eventos_user:
    path: /eventos
    controller: App\Controller\EventoController::userView

list_evento_user:
    path: /listevento
    controller: App\Controller\EventoController::list

posiciones_user:
    path: /posiciones/{id}
    controller: App\Controller\MonedaController::posiciones

proyecto_user:
    path: /proyecto
    controller: App\Controller\ComunUserController::proyecto

moneda:
    path: /moneda/{id}
    controller: App\Controller\ComunUserController::indexMoneda

list_monedas:
    path: /listmonedas/{id}
    controller: App\Controller\MonedaController::listArbolDeMonedas

list_all_monedas:
    path: /listallmonedas/{id}
    controller: App\Controller\MonedaController::listAllMonedas

invitar_moneda:
    path: /invitar/{idRuby}
    controller: App\Controller\MonedaController::invitar


#soporte

soporte_user:
   path: /soporte
   controller: App\Controller\SoporteController::indexUser

list_mensaje_user:
   path: /soporte/list
   controller: App\Controller\SoporteController::listUser

list_mensaje_new_soporte:
   path: /soporte/new/soporte
   controller: App\Controller\SoporteController::newSoporte

