dasboard_user:
   path: /
   controller: App\Controller\ComunUserController::index

edit_profile:
   path: /edituser/{id}
   controller: App\Controller\ComunUserController::edit

eventos_user:
   path: /eventos
   controller: App\Controller\EventoController::userView

list_evento_user:
   path: /listevento
   controller: App\Controller\EventoController::list

posiciones_user:
    path: /posiciones/{id}
    controller: App\Controller\MonedaController::posiciones

proyecto_user:
    path: /proyecto
    controller: App\Controller\ComunUserController::proyecto

moneda:
    path: /moneda/{id}
    controller: App\Controller\ComunUserController::indexMoneda

list_monedas:
    path: /listmonedas/{id}
    controller: App\Controller\MonedaController::listArbolDeMonedas

list_all_monedas:
    path: /listallmonedas/{id}
    controller: App\Controller\MonedaController::listAllMonedas

invitar_moneda:
    path: /invitar/{idRuby}
    controller: App\Controller\MonedaController::invitar
