admin:
   resource: "routes/admin/routes.yaml"
   prefix: /admin

profile:
   resource: "routes/user/routes.yaml"
   prefix: /profile

register:
   path: /register
   controller: App\Controller\UsersController::new

proyecto:
   path: /informacion
   controller: App\Controller\ProyectoController::index

edit_user:
   path: /edituser/{id}
   controller: App\Controller\UsersController::edit

edit_user_password:
   path: /edituserpassword/{id}
   controller: App\Controller\UsersController::editPassword
