admin:
  resource: 'routes/admin/routes.yaml'
  prefix: /admin

list_Users:
   path: /listusers
   controller: App\Controller\UsersController::list

edit_user:
   path: /edituser/{id}
   controller: App\Controller\UsersController::edit

register:
   path: /register
   controller: App\Controller\UsersController::new

delete_User:
   path: /delete/{id}
   controller: App\Controller\UsersController::delete
