dasboard:
   path: /
   controller: App\Controller\AdminController::index

posiciones_admin:
    path: /posiciones
    controller: App\Controller\AdminController::posiciones

edit_user:
   path: /edituser/{id}
   controller: App\Controller\UsersController::edit

delete_User:
   path: /delete/{id}
   controller: App\Controller\UsersController::delete

list_Users:
   path: /listusers
   controller: App\Controller\UsersController::list

eventos:
   path: /eventos
   controller: App\Controller\EventoController::adminView

new_evento:
   path: /newevento
   controller: App\Controller\EventoController::new

edit_evento:
   path: /editevento/{id}
   controller: App\Controller\EventoController::edit

delete_evento:
   path: /deleteevento/{id}
   controller: App\Controller\EventoController::delete

list_evento:
   path: /listevento
   controller: App\Controller\EventoController::list
