dasboard:
   path: /
   controller: App\Controller\AdminController::index

posiciones_admin:
   path: /posiciones
   controller: App\Controller\AdminController::posiciones
#Usuarios

delete_User:
   path: /delete/{id}
   controller: App\Controller\UsersController::delete

list_Users:
   path: /listusers
   controller: App\Controller\UsersController::list

#Eventos
eventos_admin:
   path: /eventos
   controller: App\Controller\EventoController::adminView

new_evento:
   path: /newevento
   controller: App\Controller\EventoController::new

edit_evento:
   path: /editevento/{id}
   controller: App\Controller\EventoController::edit

delete_evento:
   path: /deleteevento/{id}
   controller: App\Controller\EventoController::delete

list_evento_admin:
   path: /listevento
   controller: App\Controller\EventoController::list

#Monedas

user_list_monedas:
   path: /userlistmonedas/{id}
   controller: App\Controller\AdminController::monedasUsuario

user_list_posicion:
   path: /userlistposicion/{id}
   controller: App\Controller\AdminController::monedasPosicion

edit_invitados_moneda:
   path: /editmonedainvitados/{id}
   controller: App\Controller\MonedaController::editInvitados

edit_moneda:
   path: /editmoneda/{id}
   controller: App\Controller\MonedaController::editMoneda

new_moneda:
   path: /newmoneda/{id}
   controller: App\Controller\MonedaController::new

delete_moneda:
   path: /deletemoneda/{id}
   controller: App\Controller\MonedaController::delete

user_find_invitados:
   path: /userfindinvitados/{id}
   controller: App\Controller\MonedaController::findInvitados

find_oros:
   path: /findoros/{id}
   controller: App\Controller\MonedaController::findOrosDApoyo


posiciones_user_admin:
    path: /posiciones/{id}
    controller: App\Controller\MonedaController::posicionesAdmin



#Soporte

soporte_admin:
   path: /soporte
   controller: App\Controller\SoporteController::indexAdmin

list_mensaje_admin:
   path: /soporte/list
   controller: App\Controller\SoporteController::list

list_mensaje_delete:
   path: /soporte/delete/{id}
   controller: App\Controller\SoporteController::delete

list_mensaje_edit:
   path: /soporte/edit/{id}
   controller: App\Controller\SoporteController::edit
