name: Comprobar dependencias

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APP_ENV: dev
      APP_SECRET: ddef504d23db08e569ebd0181efc427c
      
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: composer-installer-action
      uses: nanasess/composer-installer-action@v2.0.1
    
    - name: instalar dependencias npm
      run: npm install
      

